main_backend_admin_customers:
    resource: "@MainBackendBundle/Resources/config/routing/customer.yml"
    prefix:   /admin/customers

main_backend_admin_users:
    resource: "@MainBackendBundle/Resources/config/routing/fosuser.yml"
    prefix:   /admin/users

main_backend_homepage:
    path:     /admin/
    defaults: { _controller: MainBackendBundle:Default:index }
    
main_backend_admin_customer_city:
        resource: "@MainBackendBundle/Resources/config/routing/customercity.yml"
        prefix:   /admin/customer_city

login:
    path:   /login
    defaults:   { _controller: MainBackendBundle:Security:login }

login_check:
    path:   /login_check

logout:
    path:   /logout
