<?php

namespace Main\PhotoBundle\Repository;

/**
 * AlbumPhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumPhotoRepository extends \Doctrine\ORM\EntityRepository
{
}
