main_trip:
    resource: "@MainTripBundle/Resources/config/routing.yml"
    prefix:   /

main_map:
    resource: "@MainMapBundle/Resources/config/routing.yml"
    prefix:   /

main_photo:
    resource: "@MainPhotoBundle/Resources/config/routing.yml"
    prefix:   /

main_city:
    resource: "@MainCityBundle/Resources/config/routing.yml"
    prefix:   /

main_backend:
    resource: "@MainBackendBundle/Resources/config/routing.yml"
    prefix:   /
