security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Main\BackendBundle\Entity\FosUser: bcrypt

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
    providers:
        chain_provider:
            chain:
                providers: [in_memory, user_db]
        in_memory:
            memory:
                users:
                    admin: { password: password, roles: ROLE_ADMIN }
        user_db:
            entity: { class: MainBackendBundle:FosUser, property: username }
    firewalls:
        main:
            pattern: /.*
            form_login:
                login_path: /login
                check_path: /login_check
                default_target_path: /admin
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: /logout
                target: /login
            security: true
            anonymous: true
    access_control:
        - { path: /login , roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /admin/* , roles: ROLE_USER }
        - { path: /.* , roles: IS_AUTHENTICATED_ANONYMOUSLY }
