<?php

namespace Main\BackendBundle\Repository;

/**
 * CustomerCityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerCityRepository extends \Doctrine\ORM\EntityRepository
{
}
