<?php

namespace Main\BackendBundle\Repository;

/**
 * CustomerInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
