admin_user_index:
    path:     /
    defaults: { _controller: "MainBackendBundle:FosUser:index" }
    methods:  GET

admin_user_show:
    path:     /{id}/show
    defaults: { _controller: "MainBackendBundle:FosUser:show" }
    methods:  GET

admin_user_new:
    path:     /new
    defaults: { _controller: "MainBackendBundle:FosUser:new" }
    methods:  [GET, POST]

admin_user_edit:
    path:     /{id}/edit
    defaults: { _controller: "MainBackendBundle:FosUser:edit" }
    methods:  [GET, POST]

admin_user_delete:
    path:     /{id}/delete
    defaults: { _controller: "MainBackendBundle:FosUser:delete" }
    methods:  DELETE
