admin_users_index:
    path:     /
    defaults: { _controller: "MainBackendBundle:FosUser:index" }
    methods:  GET

admin_users_show:
    path:     /{id}/show
    defaults: { _controller: "MainBackendBundle:FosUser:show" }
    methods:  GET

admin_users_new:
    path:     /new
    defaults: { _controller: "MainBackendBundle:FosUser:new" }
    methods:  [GET, POST]

admin_users_edit:
    path:     /{id}/edit
    defaults: { _controller: "MainBackendBundle:FosUser:edit" }
    methods:  [GET, POST]

admin_users_delete:
    path:     /{id}/delete
    defaults: { _controller: "MainBackendBundle:FosUser:delete" }
    methods:  DELETE
