<?php

namespace Main\CityBundle\Repository;

/**
 * AllCitiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AllCitiesRepository extends \Doctrine\ORM\EntityRepository
{
}
