<?php

namespace Main\TripBundle\Repository;

/**
 * TripCityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TripCityRepository extends \Doctrine\ORM\EntityRepository
{
}
