admin_customer_city_index:
    path:     /
    defaults: { _controller: "MainCityBundle:CustomerCity:index" }
    methods:  GET

admin_customer_city_show:
    path:     /{id}/show
    defaults: { _controller: "MainCityBundle:CustomerCity:show" }
    methods:  GET

admin_customer_city_new:
    path:     /new
    defaults: { _controller: "MainCityBundle:CustomerCity:new" }
    methods:  [GET, POST]

admin_customer_city_edit:
    path:     /{id}/edit
    defaults: { _controller: "MainCityBundle:CustomerCity:edit" }
    methods:  [GET, POST]

admin_customer_city_delete:
    path:     /{id}/delete
    defaults: { _controller: "MainCityBundle:CustomerCity:delete" }
    methods:  DELETE
